cp ../../all-codegen/codegen_tests/a1m1-test01 ./cases/test1
cp ../../all-codegen/codegen_tests/a1m1-test02 ./cases/test2
cp ../../all-codegen/codegen_tests/a1m1-test03 ./cases/test3
cp ../../all-codegen/codegen_tests/a1m1-test04 ./cases/test4
cp ../../all-codegen/codegen_tests/a1m1-test05 ./cases/test5
cp ../../all-codegen/codegen_tests/a1m1-test06 ./cases/test6
cp ../../all-codegen/codegen_tests/a1m1-test07 ./cases/test7
cp ../../all-codegen/codegen_tests/a1m1-test08 ./cases/test8
cp ../../all-codegen/codegen_tests/a1m1-test09 ./cases/test9
cp ../../all-codegen/codegen_tests/a1m1-test10 ./cases/test10
cp ../../all-codegen/codegen_tests/a1m1-test11 ./cases/test11
cp ../../all-codegen/codegen_tests/a1m1-test12 ./cases/test12
cp ../../all-codegen/codegen_tests/a1m1-test13 ./cases/test13
cp ../../all-codegen/codegen_tests/a1m1-test14 ./cases/test14
cp ../../all-codegen/codegen_tests/a1m1-test15 ./cases/test15
cp ../../all-codegen/codegen_tests/a1m1-test16 ./cases/test16
cp ../../all-codegen/codegen_tests/a1m1-test17 ./cases/test17
cp ../../all-codegen/codegen_tests/a1m1-test18 ./cases/test18
cp ../../all-codegen/codegen_tests/a1m1-test19 ./cases/test19
cp ../../all-codegen/codegen_tests/a1m1-test20 ./cases/test20
cp ../../all-codegen/codegen_tests/a1m1-test21 ./cases/test21
cp ../../all-codegen/codegen_tests/a1m1-test22 ./cases/test22
cp ../../all-codegen/codegen_tests/a1m1-test23 ./cases/test23
cp ../../all-codegen/codegen_tests/a1m1-test24 ./cases/test24
cp ../../all-codegen/codegen_tests/a1m1-test25 ./cases/test25
cp ../../all-codegen/codegen_tests/a1m1-test26 ./cases/test26
cp ../../all-codegen/codegen_tests/a1m1-test27 ./cases/test27
cp ../../all-codegen/codegen_tests/a1m1-test28 ./cases/test28
cp ../../all-codegen/codegen_tests/a1m1-test29 ./cases/test29
cp ../../all-codegen/codegen_tests/a1m1-test30 ./cases/test30
cp ../../all-codegen/codegen_tests/a1m1-test31 ./cases/test31
cp ../../all-codegen/codegen_tests/a1m1-test32 ./cases/test32
cp ../../all-codegen/codegen_tests/a1m1-test33 ./cases/test33
cp ../../all-codegen/codegen_tests/a1m1-test34 ./cases/test34
cp ../../all-codegen/codegen_tests/a1m1-test35 ./cases/test35
cp ../../all-codegen/codegen_tests/a1m1-test36 ./cases/test36
cp ../../all-codegen/codegen_tests/a1m1-test37 ./cases/test37
cp ../../all-codegen/codegen_tests/a1m1-test38 ./cases/test38
cp ../../all-codegen/codegen_tests/a1m1-test39 ./cases/test39
cp ../../all-codegen/codegen_tests/a1m1-test40 ./cases/test40
cp ../../all-codegen/codegen_tests/a1m1-test41 ./cases/test41
cp ../../all-codegen/codegen_tests/a1m1-test42 ./cases/test42
cp ../../all-codegen/codegen_tests/a1m1-test43 ./cases/test43
cp ../../all-codegen/codegen_tests/a1m1-test44 ./cases/test44
cp ../../all-codegen/codegen_tests/a1m1-test45 ./cases/test45
cp ../../all-codegen/codegen_tests/a1m1-test46 ./cases/test46
cp ../../all-codegen/codegen_tests/a1m1-test47 ./cases/test47
cp ../../all-codegen/codegen_tests/a1m1-test48 ./cases/test48
cp ../../all-codegen/codegen_tests/a1m1-test49 ./cases/test49
cp ../../all-codegen/codegen_tests/a1m1-test50 ./cases/test50