cp ../../all-codegen/codegen_tests/a1m3-test01 ./cases/test1
cp ../../all-codegen/codegen_tests/a1m3-test02 ./cases/test2
cp ../../all-codegen/codegen_tests/a1m3-test03 ./cases/test3
cp ../../all-codegen/codegen_tests/a1m3-test04 ./cases/test4
cp ../../all-codegen/codegen_tests/a1m3-test05 ./cases/test5
cp ../../all-codegen/codegen_tests/a1m3-test06 ./cases/test6
cp ../../all-codegen/codegen_tests/a1m3-test07 ./cases/test7
cp ../../all-codegen/codegen_tests/a1m3-test08 ./cases/test8
cp ../../all-codegen/codegen_tests/a1m3-test09 ./cases/test9
cp ../../all-codegen/codegen_tests/a1m3-test10 ./cases/test10
cp ../../all-codegen/codegen_tests/a1m3-test11 ./cases/test11
cp ../../all-codegen/codegen_tests/a1m3-test12 ./cases/test12
cp ../../all-codegen/codegen_tests/a1m3-test13 ./cases/test13
cp ../../all-codegen/codegen_tests/a1m3-test14 ./cases/test14
cp ../../all-codegen/codegen_tests/a1m3-test15 ./cases/test15
cp ../../all-codegen/codegen_tests/a1m3-test16 ./cases/test16
cp ../../all-codegen/codegen_tests/a1m3-test17 ./cases/test17
cp ../../all-codegen/codegen_tests/a1m3-test18 ./cases/test18
cp ../../all-codegen/codegen_tests/a1m3-test19 ./cases/test19
cp ../../all-codegen/codegen_tests/a1m3-test20 ./cases/test20
cp ../../all-codegen/codegen_tests/a1m3-test21 ./cases/test21
cp ../../all-codegen/codegen_tests/a1m3-test22 ./cases/test22
cp ../../all-codegen/codegen_tests/a1m3-test23 ./cases/test23
cp ../../all-codegen/codegen_tests/a1m3-test24 ./cases/test24
cp ../../all-codegen/codegen_tests/a1m3-test25 ./cases/test25
cp ../../all-codegen/codegen_tests/a1m3-test26 ./cases/test26
cp ../../all-codegen/codegen_tests/a1m3-test27 ./cases/test27
cp ../../all-codegen/codegen_tests/a1m3-test28 ./cases/test28
cp ../../all-codegen/codegen_tests/a1m3-test29 ./cases/test29
cp ../../all-codegen/codegen_tests/a1m3-test30 ./cases/test30
cp ../../all-codegen/codegen_tests/a1m3-test31 ./cases/test31
cp ../../all-codegen/codegen_tests/a1m3-test32 ./cases/test32
cp ../../all-codegen/codegen_tests/a1m3-test33 ./cases/test33
cp ../../all-codegen/codegen_tests/a1m3-test34 ./cases/test34
cp ../../all-codegen/codegen_tests/a1m3-test35 ./cases/test35
cp ../../all-codegen/codegen_tests/a1m3-test36 ./cases/test36
cp ../../all-codegen/codegen_tests/a1m3-test37 ./cases/test37
cp ../../all-codegen/codegen_tests/a1m3-test38 ./cases/test38
cp ../../all-codegen/codegen_tests/a1m3-test39 ./cases/test39
cp ../../all-codegen/codegen_tests/a1m3-test40 ./cases/test40
cp ../../all-codegen/codegen_tests/a1m3-test41 ./cases/test41
cp ../../all-codegen/codegen_tests/a1m3-test42 ./cases/test42
cp ../../all-codegen/codegen_tests/a1m3-test43 ./cases/test43
cp ../../all-codegen/codegen_tests/a1m3-test44 ./cases/test44
cp ../../all-codegen/codegen_tests/a1m3-test45 ./cases/test45
cp ../../all-codegen/codegen_tests/a1m3-test46 ./cases/test46
cp ../../all-codegen/codegen_tests/a1m3-test47 ./cases/test47
cp ../../all-codegen/codegen_tests/a1m3-test48 ./cases/test48
cp ../../all-codegen/codegen_tests/a1m3-test49 ./cases/test49
cp ../../all-codegen/codegen_tests/a1m3-test50 ./cases/test50